apiVersion: v2
name: landmine
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.9.3
