{{- if (and .Values.ingress.cert .Values.ingress.key) -}}
apiVersion: v1
kind: Secret
metadata:
  name: ingress-tls
data:
  tls.crt: {{ .Values.ingress.cert }}
  tls.key: {{ .Values.ingress.key }}
type: kubernetes.io/tls
{{- end -}}
