apiVersion: v1
kind: ConfigMap
metadata:
  name: landmine-config
data:
  LANDMINE_REDIS_ADDRESS: "landmine-redis-headless"
  LANDMINE_SINK_WEB_HOSTNAME: "{{ .Values.landmine.sink.web.hostname }}"
  LANDMINE_SINK_WEB_PROTOCOL: "{{ .Values.landmine.sink.web.protocol }}"
  LANDMINE_SINK_WEB_PORT: "{{ .Values.landmine.sink.web.port }}"
  LANDMINE_SINK_DNS_HOSTNAME: "{{ .Values.landmine.sink.dns.hostname }}"
  LANDMINE_SINK_EMAIL_HOSTNAME: "{{ .Values.landmine.sink.email.hostname }}"
  LANDMINE_SINK_DNS_TCP_PORT: "{{ .Values.landmine.sink.dns.tcpPort }}"
  LANDMINE_SINK_DNS_UDP_PORT: "{{ .Values.landmine.sink.dns.udpPort }}"
  LANDMINE_SINK_RDP_PORT: "{{ .Values.landmine.sink.rdp.port }}"
  LANDMINE_SINK_SMTP_PORT: "{{ .Values.landmine.sink.email.port }}"
  LANDMINE_ADMIN_SERVER_HOSTNAME: "{{ .Values.landmine.admin.hostname }}"
  LANDMINE_ADMIN_SERVER_PROTOCOL: "{{ .Values.landmine.admin.protocol }}"
  LANDMINE_BANNER_LABEL: "{{ .Values.landmine.admin.banner.label }}"
  LANDMINE_SKIN: "{{ .Values.landmine.admin.skin }}"
  LANDMINE_BANNER_CLASSIFICATION_COLOR_THEME: "{{ .Values.landmine.admin.banner.colorTheme }}"
  LANDMINE_SINK_IP_PROFILER_RANDOMIZER: "{{ .Values.landmine.sink.ipRandomizer }}"
  DEADFALL_PUBLIC_KEY: "{{ .Values.landmine.deadfall.keys.public }}"
  DEADFALL_PRIVATE_KEY: "{{ .Values.landmine.deadfall.keys.private }}"
  DNS_NAMESERVER_PREFIXES: "{{ .Values.landmine.sink.dnsNameServerPrefixes }}"
  DNS_NAMESERVER_IPS: "{{ .Values.landmine.sink.publicIps }}"
