apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "landmine.fullname" . }}
  labels:
    {{- include "landmine.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "landmine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "landmine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "landmine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: landmine-config
          ports:
            - name: admin
              containerPort: {{ .Values.landmine.admin.port }}
              protocol: TCP
            - name: sink
              containerPort: {{ .Values.landmine.sink.web.port }}
              protocol: TCP
            - name: dnstcp
              containerPort: {{ .Values.landmine.sink.dns.tcpPort }}
              protocol: TCP
            - name: dnsudp
              containerPort: {{ .Values.landmine.sink.dns.udpPort }}
              protocol: UDP
            - name: rdp
              containerPort: {{ .Values.landmine.sink.rdp.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.landmine.admin.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.landmine.admin.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
