apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  landmineOrganization: "{{ .Values.landmine.license.organization | b64enc }}"
  landmineLicense: "{{ .Values.landmine.license.key | b64enc }}"
  sesAccessKeyId: "{{ .Values.landmine.integrations.ses.accessKeyId }}"
  sesSecretAccessKey: "{{ .Values.landmine.integrations.ses.secretAccessKey }}"
