apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  notificationWebhook: {{ .Values.landmine.notificationWebhook | b64enc }}
  landmineOrganization: {{ .Values.landmine.license.organization }}
  landmineLicense: {{ .Values.landmine.license.key }}
