apiVersion: v1
kind: Service
metadata:
  name: {{ include "landmine.fullname" . }}
  labels:
    {{- include "landmine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: {{ .Values.service.admin.protocol }}
      name: admin
    - port: {{ .Values.service.sink.port }}
      targetPort: {{ .Values.service.sink.port }}
      protocol: {{ .Values.service.sink.protocol }}
      name: sink
  selector:
    {{- include "landmine.selectorLabels" . | nindent 4 }}
