apiVersion: v1
kind: Service
metadata:
  name: {{ include "landmine.fullname" . }}-tcpudp
  labels:
    {{- include "landmine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if gt (int .Values.landmine.sink.dns.tcpPort) 0 }}
    - name: dnstcp
      port: {{ .Values.landmine.sink.dns.tcpPort }}
      targetPort: {{ .Values.landmine.sink.dns.tcpPort }}
      protocol: TCP
    {{- end }}
    {{- if gt (int .Values.landmine.sink.dns.udpPort) 0 }}
    - name: dnsudp
      port: {{ .Values.landmine.sink.dns.udpPort }}
      targetPort: {{ .Values.landmine.sink.dns.udpPort }}
      protocol: UDP
    {{- end }}
    {{- if gt (int .Values.landmine.sink.rdp.port) 0 }}
    - name: rdp
      port: {{ .Values.landmine.sink.rdp.port }}
      targetPort: {{ .Values.landmine.sink.rdp.port }}
      protocol: TCP
    {{- end }}
    {{- if gt (int .Values.landmine.sink.email.port) 0 }}
    - name: smtp
      port: {{ .Values.landmine.sink.email.port }}
      targetPort: {{ .Values.landmine.sink.email.port }}
      protocol: TCP
    {{- end }}
    {{- if gt (int .Values.landmine.sink.web.port) 0 }}
    - name: web
      port: {{ .Values.landmine.sink.web.port }}
      targetPort: {{ .Values.landmine.sink.web.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "landmine.selectorLabels" . | nindent 4 }}
